# File: .readthedocs.yaml
version: 2

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

# Build PDF & ePub
formats:
  - epub
  - pdf

python:
  version: 3.8
  install:
    - requirements: doc/requirements.txt
    - method: setuptools
      path: doc
